export const projects = [
  {
    title: 'Radiology information system',
    description: "This is a software designed to manage a radiology department from the patient arrival to the billing.",
    image: '/images/covid.jpg',
    tags: ['Python', 'Django', 'HTML', 'CSS', 'Bootstrap', 'Vanilla javascript', 'Rest API', 'PostgreSQL'],
    source: '',
    visit: '',
    id: 0,
  },
  {
    title: 'Supply chain with Blockchain technology',
    description: "This is a system made that allows multiple actors of a supply chain to interact within a trusted environment and to share the same information system without worrying about confidentiality issues.",
    image: '/images/portfolio.jpg',
    tags: ['HTML', 'CSS', 'Bootstrap', 'JQuery', 'Python', 'Django', 'Hyperledger Fabric', 'Golang', 'Node.js', 'Docker'],
    source: '',
    visit: '',
    id: 1,
  },
  {
    title: 'OMG DAT CMS',
    description: "This is a lightweight content management system that allows the user to quickly create website pages in a very simple way.",
    image: '/images/abs.jpg',
    tags: ['PHP', 'Laravel', 'Vanilla Javascript', 'HTML', 'CSS', 'Bootstrap', 'MySQL'],
    source: '',
    visit: '',
    id: 2,
  },
  {
    title: 'Medical cabinet management',
    description: "This software allows to manage a medical cabinet from the patient arrival to the billing.",
    image: '/images/eb.jpg',
    tags: ['Python', ' Django', ' HTML', ' CSS', ' JQuery', ' Bootstrap', ' PostgreSQL'],
    source: 'https://github.com/lordarcadius/electrablue_mido',
    visit: 'https://forum.xda-developers.com/t/kernel-mido-oreo-pie-electrablue-kernel-21-0-july-06-redmi-note-4.3655651/',
    id: 3,
  },
  {
    title: 'Lenovo SNAPit',
    description: "Lenovo SNAPit Camera was one of the finest OEM camera apps back in those days. It had tonnes of unique and amazing features. I ported it to work on almost all devices at that time.",
    image: '/images/snapit.jpg',
    tags: ['Java', 'Libs', 'Smali'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
    id: 3,
  },
  {
    title: 'CyanogenOS Apps',
    description: "CyanogenOS 12.1 had a set of exclusive apps like a new theme engine and a new Truecaller integrated dialer. I ported it to work with CyanogenMod 13 and CM 13 based ROMs.",
    image: '/images/capps.jpg',
    tags: ['Java', 'Libs'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    id: 3,
  },

];

export const TimeLineData = [
  { year: 2015, text: 'Started my journey as a new software engineer.', },
  { year: 2016, text: 'I learned python and java with OOP programming.', },
  { year: 2017, text: 'Started working on my first project (omg-dat-cms).', },
  { year: 2018, text: 'Finished my Bachelor degree in software engineering, and started working with ELCS RESEARCH.', },
  { year: 2019, text: 'Started my master degree in AI, while still working with ELCS RESEARCH as a software engineer.', },
  { year: 2020, text: 'Finished my master degree, and started learning about blockchain technology.', },
];
